title: Киноафиша
author: Иванова Мария, Шинкевич Дарья, Быстрова Вероника
description: Проект "Киноафиша"
show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
